name: storage_space
description: Get the free, available and total storage space for the device. Utility helpers for readable sizes
version: 1.0.0
homepage: https://github.com/oodavid/storage_space
repository: https://github.com/oodavid/storage_space

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.oodavid.storage_space
        pluginClass: StorageSpacePlugin
      ios:
        pluginClass: StorageSpacePlugin

